export interface QuizQuestion {
  id: number;
  question: string;
  contextPrompt?: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
  timeLimit: number;
  baseXp: number;
}

/* ── 1. HALLO! (Greetings & Introductions) ──────────────── */
export const HALLO_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "Wie heißt du?",
    contextPrompt: "Select the English meaning",
    options: [
      "Where do you live?",
      "What is your name?",
      "Where are you from?",
      "How are you?",
    ],
    correctAnswer: "What is your name?",
    explanation: '"Wie heißt du?" translates directly to "What is your name?".',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "How do you say 'Good morning' in German?",
    contextPrompt: "Select the correct German greeting",
    options: [
      "Guten Morgen!",
      "Guten Abend!",
      "Gute Nacht!",
      "Auf Wiedersehen!",
    ],
    correctAnswer: "Guten Morgen!",
    explanation: '"Guten Morgen!" is used to greet someone in the morning until around 11 AM.',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "How do you say 'My name is Anna' in German?",
    contextPrompt: "Select the correct German phrase",
    options: [
      "Ich wohne in Anna.",
      "Ich komme aus Anna.",
      "Ich heiße Anna.",
      "Ich bin Hause Anna.",
    ],
    correctAnswer: "Ich heiße Anna.",
    explanation: '"Ich heiße..." means "My name is..." or "I am called...".',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "A: Hallo, wie geht's?\nB: ________, danke!",
    contextPrompt: "Complete the dialogue",
    options: [
      "Gut",
      "Aus Deutschland",
      "Auf Wiedersehen",
      "Ich heiße Paul",
    ],
    correctAnswer: "Gut",
    explanation: '"Gut, danke!" means "Good, thank you!", which appropriately answers "Wie geht\'s?".',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "Auf Wiedersehen!",
    contextPrompt: "Select the English meaning",
    options: [
      "Nice to meet you!",
      "See you tomorrow!",
      "Goodbye!",
      "You're welcome!",
    ],
    correctAnswer: "Goodbye!",
    explanation: '"Auf Wiedersehen" is the formal German expression for "Goodbye".',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "How do you say 'Thank you very much' in German?",
    contextPrompt: "Select the correct expression",
    options: [
      "Bitte schön!",
      "Danke schön!",
      "Entschuldigung!",
      "Guten Tag!",
    ],
    correctAnswer: "Danke schön!",
    explanation: '"Danke schön!" translates to "Thank you very much!".',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "Woher kommst du?",
    contextPrompt: "Select the English meaning",
    options: [
      "Where are you going?",
      "Where are you from?",
      "Where do you work?",
      "What is your nationality?",
    ],
    correctAnswer: "Where are you from?",
    explanation: '"Woher kommst du?" asks for a person\'s city or country of origin.',
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "Tschüss!",
    contextPrompt: "Select the English meaning",
    options: [
      "Hello!",
      "Bye!",
      "Yes!",
      "Please!",
    ],
    correctAnswer: "Bye!",
    explanation: '"Tschüss!" is the friendly, informal German word for "Bye!".',
    timeLimit: 15,
    baseXp: 100,
  },
];

/* ── 2. ZAHLEN (Numbers & Time) ─────────────────────────── */
export const ZAHLEN_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "What is the German word for the number 3?",
    contextPrompt: "Select the correct German number",
    options: ["eins", "zwei", "drei", "vier"],
    correctAnswer: "drei",
    explanation: "'drei' is the German word for 3.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "Wie viel ist 5 + 5 auf Deutsch?",
    contextPrompt: "Calculate the answer in German",
    options: ["acht", "neun", "zehn", "zwölf"],
    correctAnswer: "zehn",
    explanation: "5 + 5 = 10, which is 'zehn' in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "Wie spät ist es?",
    contextPrompt: "Select the English meaning",
    options: [
      "What day is today?",
      "What time is it?",
      "How much does it cost?",
      "Where is the station?",
    ],
    correctAnswer: "What time is it?",
    explanation: "'Wie spät ist es?' is the standard German phrase for asking the time.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "What is the German number 100?",
    contextPrompt: "Select the correct German word",
    options: ["zehn", "fünfzig", "einhundert", "eintausend"],
    correctAnswer: "einhundert",
    explanation: "'einhundert' is 100 in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "Was kommt nach 'sieben'?",
    contextPrompt: "Select the next number in sequence",
    options: ["sechs", "acht", "neun", "zehn"],
    correctAnswer: "acht",
    explanation: "After sieben (7) comes acht (8).",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "How do you say 'It is 8 o'clock' in German?",
    contextPrompt: "Select the correct German sentence",
    options: [
      "Es ist acht Uhr.",
      "Es ist acht Tage.",
      "Es ist acht Minuten.",
      "Es ist acht Jahre.",
    ],
    correctAnswer: "Es ist acht Uhr.",
    explanation: "'Es ist acht Uhr' means 'It is 8 o'clock'.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "Was bedeutet 'zwanzig'?",
    contextPrompt: "Select the English translation",
    options: ["Twelve", "Twenty", "Two", "Two hundred"],
    correctAnswer: "Twenty",
    explanation: "'zwanzig' means 20 in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "Welche Zahl ist 'fünfzehn'?",
    contextPrompt: "Select the matching number",
    options: ["5", "15", "50", "500"],
    correctAnswer: "15",
    explanation: "'fünfzehn' is 15 in German.",
    timeLimit: 15,
    baseXp: 100,
  },
];

/* ── 3. MEINE WELT (Family & People) ────────────────────── */
export const MEINE_WELT_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "How do you say 'my mother' in German?",
    contextPrompt: "Select the correct German phrase",
    options: [
      "meine Schwester",
      "meine Mutter",
      "meine Oma",
      "meine Tochter",
    ],
    correctAnswer: "meine Mutter",
    explanation: "'meine Mutter' means 'my mother'.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "Mein Bruder heißt Thomas.",
    contextPrompt: "Select the English meaning",
    options: [
      "My father is named Thomas.",
      "My brother is named Thomas.",
      "My son is named Thomas.",
      "My uncle is named Thomas.",
    ],
    correctAnswer: "My brother is named Thomas.",
    explanation: "'Bruder' means brother.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "How do you say 'my friend' (male) in German?",
    contextPrompt: "Select the correct German phrase",
    options: ["mein Freund", "meine Freundin", "mein Vater", "mein Sohn"],
    correctAnswer: "mein Freund",
    explanation: "'mein Freund' refers to a male friend.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "Das ist mein Vater.",
    contextPrompt: "Select the English translation",
    options: [
      "That is my grandfather.",
      "That is my father.",
      "That is my uncle.",
      "That is my brother.",
    ],
    correctAnswer: "That is my father.",
    explanation: "'Vater' is German for father.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "How do you say 'family' in German?",
    contextPrompt: "Select the correct noun with article",
    options: [
      "die Familie",
      "der Freund",
      "das Haus",
      "die Kinder",
    ],
    correctAnswer: "die Familie",
    explanation: "'die Familie' means the family.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "Ich habe zwei Schwestern.",
    contextPrompt: "Select the English meaning",
    options: [
      "I have two brothers.",
      "I have two sisters.",
      "I have two daughters.",
      "I have two friends.",
    ],
    correctAnswer: "I have two sisters.",
    explanation: "'Schwestern' is the plural of Schwester (sister).",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "How do you say 'my daughter' in German?",
    contextPrompt: "Select the correct German phrase",
    options: [
      "meine Schwester",
      "meine Mutter",
      "meine Tochter",
      "meine Tante",
    ],
    correctAnswer: "meine Tochter",
    explanation: "'Tochter' means daughter.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "Wir sind eine große Familie.",
    contextPrompt: "Select the English meaning",
    options: [
      "We are a small family.",
      "We are a big family.",
      "We live in a big house.",
      "We are good friends.",
    ],
    correctAnswer: "We are a big family.",
    explanation: "'große Familie' means big family.",
    timeLimit: 15,
    baseXp: 100,
  },
];

/* ── 4. ESSEN (Food & Drinks) ───────────────────────────── */
export const ESSEN_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "How do you say 'I would like a water, please' in German?",
    contextPrompt: "Select the correct German phrase",
    options: [
      "Ich möchte ein Bier, bitte.",
      "Ich möchte ein Wasser, bitte.",
      "Ich möchte einen Kaffee, bitte.",
      "Ich möchte einen Saft, bitte.",
    ],
    correctAnswer: "Ich möchte ein Wasser, bitte.",
    explanation: "'Wasser' means water, and 'bitte' means please.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "Was bedeutet 'das Brot' auf Englisch?",
    contextPrompt: "Select the English translation",
    options: ["The cheese", "The bread", "The butter", "The apple"],
    correctAnswer: "The bread",
    explanation: "'das Brot' means bread.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "How do you say 'Enjoy your meal!' in German?",
    contextPrompt: "Select the traditional German phrase",
    options: [
      "Guten Appetit!",
      "Guten Morgen!",
      "Gute Reise!",
      "Prost!",
    ],
    correctAnswer: "Guten Appetit!",
    explanation: "'Guten Appetit!' is said before starting a meal.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "Ich trinke gerne Kaffee.",
    contextPrompt: "Select the English meaning",
    options: [
      "I like drinking tea.",
      "I like drinking coffee.",
      "I want to order water.",
      "I like eating cake.",
    ],
    correctAnswer: "I like drinking coffee.",
    explanation: "'Kaffee' means coffee, and 'gerne trinken' means to enjoy drinking.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "What is 'der Apfel' in English?",
    contextPrompt: "Select the matching fruit",
    options: ["The banana", "The apple", "The orange", "The pear"],
    correctAnswer: "The apple",
    explanation: "'der Apfel' is the German word for apple.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "Die Rechnung, bitte!",
    contextPrompt: "Select the English meaning at a restaurant",
    options: [
      "The menu, please!",
      "The bill, please!",
      "More water, please!",
      "A table for two, please!",
    ],
    correctAnswer: "The bill, please!",
    explanation: "'Die Rechnung, bitte!' is used when requesting the check/bill.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "How do you say 'Cheers!' in German when drinking?",
    contextPrompt: "Select the appropriate toast",
    options: ["Prost!", "Danke!", "Bitte!", "Tschüss!"],
    correctAnswer: "Prost!",
    explanation: "'Prost!' (or 'Zum Wohl!') is used to say Cheers! in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "Was isst du zum Frühstück?",
    contextPrompt: "Select the English meaning",
    options: [
      "What do you eat for lunch?",
      "What do you eat for breakfast?",
      "What do you eat for dinner?",
      "What do you drink in the morning?",
    ],
    correctAnswer: "What do you eat for breakfast?",
    explanation: "'Frühstück' means breakfast.",
    timeLimit: 15,
    baseXp: 100,
  },
];

/* ── 5. DEUTSCHLAND (Cities & Culture) ──────────────────── */
export const DEUTSCHLAND_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "Was ist die Hauptstadt von Deutschland?",
    contextPrompt: "Select the capital city of Germany",
    options: ["München", "Hamburg", "Berlin", "Frankfurt"],
    correctAnswer: "Berlin",
    explanation: "Berlin is the capital and largest city of Germany.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "In welcher Stadt steht das Brandenburger Tor?",
    contextPrompt: "Select the city where Brandenburg Gate is located",
    options: ["Köln", "Berlin", "Stuttgart", "Leipzig"],
    correctAnswer: "Berlin",
    explanation: "The famous Brandenburg Gate (Brandenburger Tor) is located in Berlin.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "Welche Stadt ist bekannt für das Oktoberfest?",
    contextPrompt: "Select the famous Oktoberfest city",
    options: ["Frankfurt", "Hamburg", "München", "Düsseldorf"],
    correctAnswer: "München",
    explanation: "Oktoberfest is held annually in Munich (München), Bavaria.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "Wo steht der berühmte Kölner Dom?",
    contextPrompt: "Select the city of Cologne Cathedral",
    options: ["Köln", "Bonn", "Mainz", "Dresden"],
    correctAnswer: "Köln",
    explanation: "The Cologne Cathedral (Kölner Dom) is located in Cologne (Köln).",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "How do you say 'Germany' in German?",
    contextPrompt: "Select the official German country name",
    options: ["Deutschland", "Österreich", "Schweiz", "Europa"],
    correctAnswer: "Deutschland",
    explanation: "Germany is called 'Deutschland' in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "Welche Währung nutzt man in Deutschland?",
    contextPrompt: "Select the official currency",
    options: ["Franken", "Pfund", "Euro", "Mark"],
    correctAnswer: "Euro",
    explanation: "Germany uses the Euro (€) as its official currency.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "Was ist die zweite Sprache in der Schweiz neben Deutsch?",
    contextPrompt: "Select one of the official Swiss languages",
    options: ["Französisch", "Spanisch", "Schwedisch", "Niederländisch"],
    correctAnswer: "Französisch",
    explanation: "French (Französisch), along with German, Italian, and Romansh, is an official language of Switzerland.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "In welcher Stadt liegt der große Hafen an der Elbe?",
    contextPrompt: "Select the major port city",
    options: ["Bremen", "Hamburg", "Rostock", "Kiel"],
    correctAnswer: "Hamburg",
    explanation: "Hamburg has the largest sea port in Germany, located on the Elbe river.",
    timeLimit: 15,
    baseXp: 100,
  },
];

/* ── 6. UNTERWEGS (Directions & Transport) ──────────────── */
export const UNTERWEGS_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    question: "Wo ist der Bahnhof?",
    contextPrompt: "Select the English meaning",
    options: [
      "Where is the airport?",
      "Where is the train station?",
      "Where is the bus stop?",
      "Where is the hotel?",
    ],
    correctAnswer: "Where is the train station?",
    explanation: "'Bahnhof' means train station in German.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 2,
    question: "How do you say 'straight ahead' when giving directions in German?",
    contextPrompt: "Select the correct direction phrase",
    options: ["geradeaus", "nach links", "nach rechts", "zurück"],
    correctAnswer: "geradeaus",
    explanation: "'geradeaus' means straight ahead.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 3,
    question: "Was bedeutet 'Biegen Sie links ab'?",
    contextPrompt: "Select the English translation",
    options: [
      "Turn right",
      "Turn left",
      "Go straight",
      "Stop here",
    ],
    correctAnswer: "Turn left",
    explanation: "'links abbiegen' means to turn left.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 4,
    question: "Eine Fahrkarte nach Berlin, bitte.",
    contextPrompt: "Select the English meaning",
    options: [
      "A flight to Berlin, please.",
      "A ticket to Berlin, please.",
      "A map of Berlin, please.",
      "A hotel in Berlin, please.",
    ],
    correctAnswer: "A ticket to Berlin, please.",
    explanation: "'Fahrkarte' means travel ticket.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 5,
    question: "How do you say 'on the right side' in German?",
    contextPrompt: "Select the correct phrase",
    options: ["auf der rechten Seite", "auf der linken Seite", "in der Mitte", "weit weg"],
    correctAnswer: "auf der rechten Seite",
    explanation: "'rechts' means right.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 6,
    question: "Wann fährt der nächste Zug?",
    contextPrompt: "Select the English meaning",
    options: [
      "Where does the train stop?",
      "When does the next train leave?",
      "How much is the train ticket?",
      "Is this the train to Berlin?",
    ],
    correctAnswer: "When does the next train leave?",
    explanation: "'Zug' means train, and 'wann fährt... ab/abfahren' asks for departure time.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 7,
    question: "Was bedeutet 'der Flughafen'?",
    contextPrompt: "Select the English translation",
    options: ["The bus station", "The airport", "The harbor", "The taxi stand"],
    correctAnswer: "The airport",
    explanation: "'der Flughafen' means airport.",
    timeLimit: 15,
    baseXp: 100,
  },
  {
    id: 8,
    question: "How do you say 'Excuse me, where is...' in German?",
    contextPrompt: "Select the polite question opener",
    options: [
      "Entschuldigung, wo ist...",
      "Guten Tag, wer ist...",
      "Bitte sehr, was ist...",
      "Auf Wiedersehen, wie ist...",
    ],
    correctAnswer: "Entschuldigung, wo ist...",
    explanation: "'Entschuldigung, wo ist...' means 'Excuse me, where is...'.",
    timeLimit: 15,
    baseXp: 100,
  },
];

export const QUESTIONS_BY_QUIZ_ID: Record<string, QuizQuestion[]> = {
  hallo: HALLO_QUESTIONS,
  zahlen: ZAHLEN_QUESTIONS,
  "meine-welt": MEINE_WELT_QUESTIONS,
  essen: ESSEN_QUESTIONS,
  deutschland: DEUTSCHLAND_QUESTIONS,
  unterwegs: UNTERWEGS_QUESTIONS,
};

export function getQuestionsForQuiz(quizId: string): QuizQuestion[] {
  return QUESTIONS_BY_QUIZ_ID[quizId] || HALLO_QUESTIONS;
}
